import type { Metadata } from "next";
import "./globals.css";
import { SiteHeader } from "@/components/layouts/lobby/site-header";
import { SiteFooter } from "@/components/layouts/lobby/site-footer";
import { leagueSpartan, rethink } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${leagueSpartan.className} ${rethink.className}`}>
        <SiteHeader />
        <main>{children}</main>
        <SiteFooter />
      </body>
    </html>
  );
}
